### ISSUE TITLE
ImageMagick-windows.zip doesn't seem to exist on the FTP server anymore.

### ISSUE THREAD

**Issue by silverbacknet** [ImageMagick/Website#12]
This seems like a reasonably place to raise the issue, but ImageMagick-windows.zip doesn't seem to be on either the http or ftp site anymore. https://www.imagemagick.org/download/windows/ImageMagick-windows.zip and ftp://ftp.imagemagick.org/pub/ImageMagick/windows/ImageMagick-windows.zip are missing. Oddly enough, the signature files are still there, though.

**Comment by urban-warrior** [comment]
Appears to be fixed.
