### ISSUE TITLE
website is not loading

### ISSUE THREAD

**Issue by Izopi4a** [ImageMagick/Website#26]
Hi,

https://www.imagemagick.org/ does not open for me 

`ERR_CONNECTION_REFUSED`

**Comment by dlemstra** [comment]
Works on my machine now.

**Comment by Izopi4a** [comment]
working on my end as well. Thanks!

**Comment by kubikanber** [comment]
Hi,
https://www.imagemagick.org/ does not working.

https://www.isitdownrightnow.com/imagemacik.org.html

Imagemacik.org Server Status Check

Imagemacik
Website Name: imagemacik.org
URL Checked: no response
Response Time: unknown
Last Down: DOWN
Imagemacik.org is DOWN for everyone.
It is not just you. The server is not responding...

**Comment by dlemstra** [comment]
Please don't use issues to report this.
