### ISSUE TITLE
is Imagemacik.org  DOWN for everyone?

### ISSUE THREAD

**Issue by kubikanber** [ImageMagick/Website#27]
Hi,
https://www.imagemagick.org/ does not working.

https://www.isitdownrightnow.com/imagemacik.org.html

Imagemacik.org Server Status Check

Imagemacik
Website Name: imagemacik.org
URL Checked: no response
Response Time: unknown
Last Down: DOWN
Imagemacik.org is DOWN for everyone.
It is not just you. The server is not responding...

_Originally posted by @kubikanber in https://github.com/ImageMagick/Website/issues/26#issuecomment-500851167_

**Comment by dlemstra** [comment]
This is not the place to report this. And yes the server is down at the moment.
