### ISSUE TITLE
PGM isn't supposed to have a linear color space

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/Website#29]
[This page of the website](https://imagemagick.org/script/color-management.php) says:

> A majority of the image formats assume an sRGB colorspace (e.g. JPEG, PNG, etc.). A few support only linear RGB (e.g. EXR, DPX, CIN, HDR) or **only** linear GRAY (e.g. **PGM**).

Well, according to [Netpbm's website](http://netpbm.sourceforge.net/doc/pgm.html):

> Note that a common variation from the PGM format is to have the gray value be "linear," i.e. as specified above except without the gamma adjustment. *pnmgamma* takes such a PGM variant as input and produces a true PGM as output.
>
> Another popular variation from PGM is to substitute the newer sRGB transfer function for the BT.709 one. You can use *pnmgamma* to convert between this variation and true PGM.

If ImageMagick supports a nonstandard variant of PGM (or ***only*** a nonstandard variant), then this fact should be noted somewhere. PGM is not linear.

**Comment by urban-warrior** [comment]
We'll correct the documentation.  PGM is not linear.
