### ISSUE TITLE
Website redesign?

### ISSUE THREAD

**Issue by purpledrosophila** [ImageMagick/Website#30]
Hi all,

I was looking over the source code for the ImageMagick website, and I noticed that a lot of things haven't been updated in multiple years. I'm both a technical writer and an expert on web accessibility, and I can see many places where updating the layout and organization of the website could be a major help to people, even if we left the content exactly the way it is right now. May I create a mockup of an accessible template, CSS, and JavaScript that may be better suited for modern accessibility concerns? 

I know there are at least a few significant bugs that could use correction which I have found, including:
1. The hamburger menu for small screens doesn't work if JavaScript is turned off.
2. Hamburger menus by definition are not accessible to people with mobility impairments.
3. Links are not underlined, which could cause confusion for people with cognitive disabilities.
4. Many areas of the site do not have enough contrast to be seen easily by people with low vision
5. Tables containing technical data can be difficult for screen readers to parse properly.

This is not meant to say that the ImageMagick site is terrible, by the way -- far from it. The fact is, though, that over 95% of sites have significant accessibility problems, and as long as that's true, people with disabilities will have a very hard time using the web. If the site is fully accessible, on the other hand, ImageMagick will be ahead of the curve.

Please let me know if creating a new site template like this would be a viable thing to do. I would also be willing to be a contact point for standardizing the documentation and keeping it accessible in the future, if you have need for someone like that.

**Comment by urban-warrior** [comment]
We have had a number of volunteers that worked on improving the website over the years only for them to disappear and leave us to support their work.  To prevent that from happening again, we designed the web site to be easy to maintain by putting all content in the `include` folder and leveraging Twitter's Bootstrap CSS.  All local CSS customizations land in `magick-css.php` and local Javascript customizations land in `magick-js.php`.  If you can work within these constraints, feel free to enhance the web site and improve accessibility.

**Comment by purpledrosophila** [comment]
I understand exactly what you mean; that's extremely unprofessional of them. I have needed to untangle code left behind in those situations myself, and it's a nightmare. I don't see the files you're referring to in the code root, but I will look more carefully.

Would it be okay if for the first few commits, I create a new self-contained folder in the repository? I don't want to risk breaking anything that's already there, and it's easier to do cross-browser testing with something self-contained. I would like to create a developer documentation folder as well, if that would be OK, so the new website structure I'm creating is well-documented.

Also, how devoted are you to supporting Internet Explorer and Microsoft Edge? To my understanding, the two of them together take up less than 5% of total browser share, and Microsoft Edge is not going to even be offered as a consumer browser after this year. They also don't have the accessibility features of modern browsers. From an accessibility standpoint, I've pretty much abandoned supporting Microsoft browsers. Any web templates I build have an aside in them that, if a Microsoft browser is detected, just shows a link to reference a more modern browser. No specific one, of course, don't want to act like I'm endorsing a specific company. 

And one last question -- hope you didn't mind the rambling -- is there any specific time that you'd prefer to have the new site ready by? I don't know how much time I'll be able to devote to this on a consistent basis, but if you need something quick, I might be able to make it work.

**Comment by urban-warrior** [comment]
Clone the website repo and work directly on the clone.  When its ready, we'll take a look to ensure its a suitable replacement for the existing website and make the switch.

Doesn't Twitter's Bootstrap CSS have kludges to support IE and Edge?  We certainly want to try to support these browsers as best we can accept a diminished experience.

You have all the time in the world to deliver the site.  The existing site certainly meets minimum standards for delivering ImageMagick content.  That gives you ample time to deliver your improved UI.
