### ISSUE TITLE
-pointsize also affects fonts

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/Website#65]
Please see https://github.com/ImageMagick/ImageMagick/pull/3038

I apologize. I do not know how to transfer pull request from one repository to another.

**Comment by urban-warrior** [comment]
Thanks for your contribution to the open-source ImageMagick project.  Since it was a minor change, we manually applied your patch to the web pages @ imagemagick.org.  The changes will migrate to the ImageMagick source distribution eventually.
