### ISSUE TITLE
Navbar covers text

### ISSUE THREAD

**Issue by Jmuccigr** [ImageMagick/Website#67]
On the command-line options page (for example), the navbar covers the top of the text window, which is fine except when you use the links to move around the page, the lin-text ends up under the navbar. This seems like a (probably) easy thing to fix in the css.

Not sure what it is, but it seems like the kind of thing that would be accounted for somehow. :-)

**Comment by urban-warrior** [comment]
Which browser are you using?  We're using modern releases of Chrome and Firefox and we're not seeing the problem you mentioned.

**Comment by Jmuccigr** [comment]
Safari on MacOS is my usual, but I find that it happens in iOS also for Safari and Firefox. On my laptop it's ok in FireFox and Chrome, as you report.

**Comment by Jmuccigr** [comment]
OK, this seems to be a [known issue](https://github.com/mdn/browser-compat-data/issues/4945#issuecomment-748449872) with Safari (not sure about iOS). Hopefully fixed in next update.

**Comment by dakur** [comment]
It is in 14.1. ;-) See https://github.com/mdn/browser-compat-data/pull/10129

**Comment by Jmuccigr** [comment]
> It is in 14.1. ;-) See [mdn/browser-compat-data#10129](https://github.com/mdn/browser-compat-data/pull/10129)

Not for me.

**Comment by dakur** [comment]
I don't know. 🤷‍♂️ I just saw link to here from the issue I referenced above so I just wrote that that is fixed in Safari. 🙂
