### ISSUE TITLE
legacy site css?

### ISSUE THREAD

**Issue by Jmuccigr** [ImageMagick/Website#68]
Is there any interest in improving the look of very helpful legacy "Usage" pages with some simple css? Every time I check them I feel transported to the late 1990s. :-)

I've got a little bookmarklet that just applies the following rules and it makes those pages a lot more readable:

```
body {
  background-color:white;
  margin-right:10%;
  margin-left:10%;
  font-family:"Gill Sans"
}
tr {
  margin:1em;
}
```

**Comment by urban-warrior** [comment]
See https://github.com/ImageMagick/Usage.  You can post a PR.  In the mean-time, we applied your style sheet to the Usage pages.
