### ISSUE TITLE
Site update

### ISSUE THREAD

**Issue by dazld** [ImageMagick/Website#8]
I'd like to help convert the site to something more modern - thinking jekyll, or some other static site gen, with the content in some style agnostic format such as markdown. 

Are there any plans to do something like this already..? If so, how can I help out?

(motivation, I'd like to give something back to the IM project, and have a useful resource for myself too!)

**Comment by darrylyoung** [comment]
Sounds good. Count me in.

**Comment by urban-warrior** [comment]
A website modernization is fine with us.  We have a few minor conditions:

* Any web site support software must run on CentOS 7, the OS installed @ www.imagemagick.org;
* The software needs to be easy to maintain for the ImageMagick developers so we can readily edit the web site content;
* It must be simple to mirror the web site, we mirror www.imagemagick.org to create the static web pages in the source distribution of ImageMagick.

We had another offer to modernize the web site with Wordpress.  We will contact them and ask them to report their status here.  We do not think they have started yet.  Perhaps they can collaborate with you.

**Comment by dazld** [comment]
totally fine with all your requirements as above. would love to swap ideas with others too, if they are still interested. 

Current thinking is something like the [sinon docs](https://github.com/sinonjs/sinon/tree/master/docs) setup - would this be ok? You seem to have mostly static content, anything dynamic can be special cased.

**Comment by dlemstra** [comment]
@dazld and @darrylyoung A while back there was also an attempt to change the usage documentation from Anthony to markdown: https://github.com/ImageMagick/usage-markdown. Maybe you could also assist us with that? I have no idea what the current status of that project is though.

**Comment by strutagency** [comment]
Sounds like a great idea @dazld and @darrylyoung. If you need any design support, please let us know. We are happy to assist.

**Comment by dazld** [comment]
I'm still interested in helping out! 

What originally prompted reaching out was coming across some very [bare bones pages](http://www.imagemagick.org/Usage/) via a search - are these pages current...?

**Comment by urban-warrior** [comment]
Anthony's usage pages are maintained independently of the rest of the ImageMagick web site.  You can contact Anthony directly @ the email address listed near the bottom of the page.

**Comment by MarkSetchell** [comment]
@dazld and @darrylyoung 

If you would care to Email me, I can give you an update on the project to convert Anthony's "ImageMagick Usage" pages to markdown. My name is "mark" and my family are "TheSetchells" so you should be able to work out my Email address as its a dot com.

Dirk - If you care to Email me too, I would have your Email address and we could all discuss things.

**Comment by emcconville** [comment]
@MarkSetchell & @urban-warrior 

Happy to help w/ Anthony's work over at the [usage-markdown](https://github.com/ImageMagick/usage-markdown) project. It was intended to use [Pandoc](http://pandoc.org) as document processor to transpose(?) markdown source files to both HTML and Bash scripts. The latter being used to generate image resources reference by HTML.
