### ISSUE TITLE
Switch "Version" and "Description" columns on downloads page

### ISSUE THREAD

**Issue by ad-si** [ImageMagick/Website#85]
I think it's quite confusing that the description / title comes after the download link.
Point in case: I just read over "macOS High Sierra" several times (https://imagemagick.org/script/download.php#macosx) and opened [an Issue](https://github.com/ImageMagick/ImageMagick/issues/4676) that I can't install it on macOS Monterey 😅

**Comment by dlemstra** [comment]
For the other downloads this order makes more sense to me. The Windows downloads have a longer description with more details and I don't think I would want that as the first column there. Any other suggestions on how we could make this more clear?

**Comment by ad-si** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/36796532/148652198-652b3557-9a35-4088-a0e0-c8b8f5e8671d.png)
The information should probably be better split between first and last column
