### ISSUE TITLE
Confusing Mixup in Porting Guide?

### ISSUE THREAD

**Issue by kalinni** [ImageMagick/Website#92]
Hi there,

the porting guide says` The "magick" command is the new primary command of the Shell API, replacing the old "magick" command.` in the Command Changes section (https://imagemagick.org/script/porting.php#cli). I think it replaced the old "convert" command?

Also the same section has
`To reduce the footprint of the command-line utilities, these utilities are symbolic links to the magick utility. You can also invoke them from the magick utility, for example, use magick logo: logo.png to invoke the magick utility. `
which probably also is supposed to have another command but magick at the end?

Thanks and cheers,
Katja

**Comment by fmw42** [comment]
magick is the new convert in IM 7.  But all the other tools (mogrify, identify ...) are still old and have not been updated. To call the new convert, just use magick.  But to call the old IM 6 tools preface each with mogrify (no ending mogrify). So magick identify, magick mogrify, magick montage, etc

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
