### ISSUE TITLE
Doc fix for -quality

### ISSUE THREAD

**Issue by geitda** [ImageMagick/Website#94]
The `-quality`  section at https://github.com/ImageMagick/Website/blob/eca12972c1628fcad2b5aeb6a9a7fe11b7b36342/include/command-line-options.php#L6101 is wrong.
"Greater than 90" means 91 through 100, but quality **equal** to 90 is also not downsampled.

Reproduce with:
```
magick convert -quality 91 logo: JPG:- | magick identify -format %[jpeg:sampling-factor]\n -
1x1,1x1,1x1

magick convert -quality 90 logo: JPG:- | magick identify -format %[jpeg:sampling-factor]\n -
1x1,1x1,1x1

magick convert -quality 89 logo: JPG:- | magick identify -format %[jpeg:sampling-factor]\n -
2x2,1x1,1x1
```

Fix is to change the documentation to either "When the quality is greater than or equal to 90" or "When the quality is 90 or greater" (I'm not a fan of "greater than 89" but that's equivalent)

**Comment by dlemstra** [comment]
Feel free to open a pull request to change this otherwise we will change that this weekend ourselves.

**Comment by dlemstra** [comment]
We have made the change that you suggested.
